---
  - name: "Copy rpm to server"
    copy:
      src: filebeat-5.2.2-x86_64.rpm
      dest: "/root/filebeat-5.2.2-x86_64.rpm"
  - name: "Install filebeat via RPM"
    yum:
      name: /root/filebeat-5.2.2-x86_64.rpm
      state: present
  - name: "Copy config file"
    copy:
      src: filebeat.yml
      dest: "/etc/filebeat/filebeat.yml"
  - name: "Start and enable filebeat"
    systemd:
      name: filebeat
      enabled: yes
      state: started
